// Generated by Wrangler by running `wrangler types`

interface Env {
	CACHE_KV: KVNamespace;
	JWT_SECRET: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_PUBLISHABLE_KEY: string;
	CLOUDFLARE_ACCESS_AUD: string;
	ENVIRONMENT: string;
	PRODUCTS_R2: R2Bucket;
	CMS_R2: R2Bucket;
	DB: D1Database;
}
