//
// ApiCheckoutGuestPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiCheckoutGuestPost200Response: Codable, JSONEncodable, Hashable {

    public var success: Bool
    public var orderId: String
    public var clientSecret: String?

    public init(success: Bool, orderId: String, clientSecret: String? = nil) {
        self.success = success
        self.orderId = orderId
        self.clientSecret = clientSecret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case orderId
        case clientSecret
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(orderId, forKey: .orderId)
        try container.encodeIfPresent(clientSecret, forKey: .clientSecret)
    }
}

