//
// Checkout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Checkout: Codable, JSONEncodable, Hashable {

    public var email: String?
    public var customerId: UUID?
    public var couponCode: String?
    public var address: CheckoutAddress?
    public var shippingAddressJson: [String: AnyCodable]?
    public var billingAddressJson: [String: AnyCodable]?
    public var items: [CheckoutItemsInner]
    public var affiliateId: String?
    public var utmSource: String?
    public var utmMedium: String?
    public var utmCampaign: String?
    public var acceptsMarketing: Bool?

    public init(email: String? = nil, customerId: UUID? = nil, couponCode: String? = nil, address: CheckoutAddress? = nil, shippingAddressJson: [String: AnyCodable]? = nil, billingAddressJson: [String: AnyCodable]? = nil, items: [CheckoutItemsInner], affiliateId: String? = nil, utmSource: String? = nil, utmMedium: String? = nil, utmCampaign: String? = nil, acceptsMarketing: Bool? = nil) {
        self.email = email
        self.customerId = customerId
        self.couponCode = couponCode
        self.address = address
        self.shippingAddressJson = shippingAddressJson
        self.billingAddressJson = billingAddressJson
        self.items = items
        self.affiliateId = affiliateId
        self.utmSource = utmSource
        self.utmMedium = utmMedium
        self.utmCampaign = utmCampaign
        self.acceptsMarketing = acceptsMarketing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case customerId = "customer_id"
        case couponCode = "coupon_code"
        case address
        case shippingAddressJson = "shipping_address_json"
        case billingAddressJson = "billing_address_json"
        case items
        case affiliateId = "affiliate_id"
        case utmSource = "utm_source"
        case utmMedium = "utm_medium"
        case utmCampaign = "utm_campaign"
        case acceptsMarketing = "accepts_marketing"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(couponCode, forKey: .couponCode)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(shippingAddressJson, forKey: .shippingAddressJson)
        try container.encodeIfPresent(billingAddressJson, forKey: .billingAddressJson)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(affiliateId, forKey: .affiliateId)
        try container.encodeIfPresent(utmSource, forKey: .utmSource)
        try container.encodeIfPresent(utmMedium, forKey: .utmMedium)
        try container.encodeIfPresent(utmCampaign, forKey: .utmCampaign)
        try container.encodeIfPresent(acceptsMarketing, forKey: .acceptsMarketing)
    }
}

