//
// Checkout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Checkout: Codable, JSONEncodable, Hashable {

    public static let redeemPointsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var email: String?
    public var customerId: UUID?
    public var couponCode: String?
    public var locationId: String?
    public var address: CheckoutAddress?
    public var shippingAddressJson: [String: AnyCodable]?
    public var billingAddressJson: [String: AnyCodable]?
    public var items: [CheckoutItemsInner]
    public var affiliateId: String?
    public var utmSource: String?
    public var utmMedium: String?
    public var utmCampaign: String?
    public var acceptsMarketing: CheckoutAcceptsMarketing?
    public var turnstileToken: String?
    public var redeemPoints: Int?
    public var b2bCompany: String?
    public var b2bVatId: String?

    public init(email: String? = nil, customerId: UUID? = nil, couponCode: String? = nil, locationId: String? = nil, address: CheckoutAddress? = nil, shippingAddressJson: [String: AnyCodable]? = nil, billingAddressJson: [String: AnyCodable]? = nil, items: [CheckoutItemsInner], affiliateId: String? = nil, utmSource: String? = nil, utmMedium: String? = nil, utmCampaign: String? = nil, acceptsMarketing: CheckoutAcceptsMarketing? = nil, turnstileToken: String? = nil, redeemPoints: Int? = nil, b2bCompany: String? = nil, b2bVatId: String? = nil) {
        self.email = email
        self.customerId = customerId
        self.couponCode = couponCode
        self.locationId = locationId
        self.address = address
        self.shippingAddressJson = shippingAddressJson
        self.billingAddressJson = billingAddressJson
        self.items = items
        self.affiliateId = affiliateId
        self.utmSource = utmSource
        self.utmMedium = utmMedium
        self.utmCampaign = utmCampaign
        self.acceptsMarketing = acceptsMarketing
        self.turnstileToken = turnstileToken
        self.redeemPoints = redeemPoints
        self.b2bCompany = b2bCompany
        self.b2bVatId = b2bVatId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case customerId = "customer_id"
        case couponCode = "coupon_code"
        case locationId = "location_id"
        case address
        case shippingAddressJson = "shipping_address_json"
        case billingAddressJson = "billing_address_json"
        case items
        case affiliateId = "affiliate_id"
        case utmSource = "utm_source"
        case utmMedium = "utm_medium"
        case utmCampaign = "utm_campaign"
        case acceptsMarketing = "accepts_marketing"
        case turnstileToken
        case redeemPoints = "redeem_points"
        case b2bCompany = "b2b_company"
        case b2bVatId = "b2b_vat_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(couponCode, forKey: .couponCode)
        try container.encodeIfPresent(locationId, forKey: .locationId)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(shippingAddressJson, forKey: .shippingAddressJson)
        try container.encodeIfPresent(billingAddressJson, forKey: .billingAddressJson)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(affiliateId, forKey: .affiliateId)
        try container.encodeIfPresent(utmSource, forKey: .utmSource)
        try container.encodeIfPresent(utmMedium, forKey: .utmMedium)
        try container.encodeIfPresent(utmCampaign, forKey: .utmCampaign)
        try container.encodeIfPresent(acceptsMarketing, forKey: .acceptsMarketing)
        try container.encodeIfPresent(turnstileToken, forKey: .turnstileToken)
        try container.encodeIfPresent(redeemPoints, forKey: .redeemPoints)
        try container.encodeIfPresent(b2bCompany, forKey: .b2bCompany)
        try container.encodeIfPresent(b2bVatId, forKey: .b2bVatId)
    }
}

