//
// CheckoutAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckoutAddress: Codable, JSONEncodable, Hashable {

    public var fullname: String?
    public var address: String?
    public var zipcode: String?

    public init(fullname: String? = nil, address: String? = nil, zipcode: String? = nil) {
        self.fullname = fullname
        self.address = address
        self.zipcode = zipcode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullname
        case address
        case zipcode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fullname, forKey: .fullname)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(zipcode, forKey: .zipcode)
    }
}

