//
// Coupon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Coupon: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case percent = "percent"
        case fixed = "fixed"
        case freeship = "freeship"
        case percentage = "percentage"
        case freeShipping = "free_shipping"
    }
    public var id: UUID
    public var code: String
    public var type: ModelType
    public var value: Double
    public var maxUses: Int?
    public var uses: Int? = 0
    public var expiresAt: Int?
    public var isActive: Bool? = true
    public var createdAt: Date

    public init(id: UUID, code: String, type: ModelType, value: Double, maxUses: Int? = nil, uses: Int? = 0, expiresAt: Int? = nil, isActive: Bool? = true, createdAt: Date) {
        self.id = id
        self.code = code
        self.type = type
        self.value = value
        self.maxUses = maxUses
        self.uses = uses
        self.expiresAt = expiresAt
        self.isActive = isActive
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case code
        case type
        case value
        case maxUses = "max_uses"
        case uses
        case expiresAt = "expires_at"
        case isActive = "is_active"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(code, forKey: .code)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
        try container.encodeIfPresent(maxUses, forKey: .maxUses)
        try container.encodeIfPresent(uses, forKey: .uses)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Coupon: Identifiable {}
