//
// FulfillmentItemsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FulfillmentItemsInner: Codable, JSONEncodable, Hashable {

    public static let quantityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var orderItemId: UUID
    public var quantity: Int

    public init(orderItemId: UUID, quantity: Int) {
        self.orderItemId = orderItemId
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderItemId = "order_item_id"
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderItemId, forKey: .orderItemId)
        try container.encode(quantity, forKey: .quantity)
    }
}

