//
// Fulfillment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Fulfillment: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case processing = "processing"
        case shipped = "shipped"
        case delivered = "delivered"
        case cancelled = "cancelled"
    }
    public var id: UUID
    public var orderId: UUID
    public var status: Status? = .processing
    public var trackingNumber: String?
    public var carrier: String?
    public var shippedAt: Date?
    public var items: [FulfillmentItemsInner]?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, orderId: UUID, status: Status? = .processing, trackingNumber: String? = nil, carrier: String? = nil, shippedAt: Date? = nil, items: [FulfillmentItemsInner]? = nil, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.orderId = orderId
        self.status = status
        self.trackingNumber = trackingNumber
        self.carrier = carrier
        self.shippedAt = shippedAt
        self.items = items
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case orderId = "order_id"
        case status
        case trackingNumber = "tracking_number"
        case carrier
        case shippedAt = "shipped_at"
        case items
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(orderId, forKey: .orderId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(trackingNumber, forKey: .trackingNumber)
        try container.encodeIfPresent(carrier, forKey: .carrier)
        try container.encodeIfPresent(shippedAt, forKey: .shippedAt)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Fulfillment: Identifiable {}
