//
// GuestCheckoutItemsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GuestCheckoutItemsInner: Codable, JSONEncodable, Hashable {

    public static let quantityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var variationId: UUID
    public var quantity: Int

    public init(variationId: UUID, quantity: Int) {
        self.variationId = variationId
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case variationId = "variation_id"
        case quantity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(variationId, forKey: .variationId)
        try container.encode(quantity, forKey: .quantity)
    }
}

