//
// GuestCheckout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GuestCheckout: Codable, JSONEncodable, Hashable {

    public var email: String
    public var shippingAddress: GuestCheckoutShippingAddress
    public var items: [GuestCheckoutItemsInner]
    public var affiliateId: String?

    public init(email: String, shippingAddress: GuestCheckoutShippingAddress, items: [GuestCheckoutItemsInner], affiliateId: String? = nil) {
        self.email = email
        self.shippingAddress = shippingAddress
        self.items = items
        self.affiliateId = affiliateId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case shippingAddress = "shipping_address"
        case items
        case affiliateId = "affiliate_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(shippingAddress, forKey: .shippingAddress)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(affiliateId, forKey: .affiliateId)
    }
}

