//
// GuestCheckoutShippingAddress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GuestCheckoutShippingAddress: Codable, JSONEncodable, Hashable {

    public var fullname: String
    public var address: String
    public var zipcode: String

    public init(fullname: String, address: String, zipcode: String) {
        self.fullname = fullname
        self.address = address
        self.zipcode = zipcode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullname
        case address
        case zipcode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fullname, forKey: .fullname)
        try container.encode(address, forKey: .address)
        try container.encode(zipcode, forKey: .zipcode)
    }
}

