//
// Product.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Product: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case draft = "draft"
        case published = "published"
        case archived = "archived"
    }
    public var id: UUID
    public var slug: String
    public var title: String
    public var description: String?
    public var status: Status? = .draft
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, slug: String, title: String, description: String? = nil, status: Status? = .draft, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.slug = slug
        self.title = title
        self.description = description
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case slug
        case title
        case description
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(slug, forKey: .slug)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Product: Identifiable {}
