//
// Review.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Review: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case pending = "pending"
        case approved = "approved"
        case rejected = "rejected"
    }
    public static let ratingRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 5, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID
    public var productId: UUID
    public var customerId: UUID?
    public var rating: Int
    public var comment: String?
    public var status: Status? = .pending
    public var verifiedPurchase: Bool? = false
    public var createdAt: Date

    public init(id: UUID, productId: UUID, customerId: UUID? = nil, rating: Int, comment: String? = nil, status: Status? = .pending, verifiedPurchase: Bool? = false, createdAt: Date) {
        self.id = id
        self.productId = productId
        self.customerId = customerId
        self.rating = rating
        self.comment = comment
        self.status = status
        self.verifiedPurchase = verifiedPurchase
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case productId = "product_id"
        case customerId = "customer_id"
        case rating
        case comment
        case status
        case verifiedPurchase = "verified_purchase"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(productId, forKey: .productId)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encode(rating, forKey: .rating)
        try container.encodeIfPresent(comment, forKey: .comment)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(verifiedPurchase, forKey: .verifiedPurchase)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Review: Identifiable {}
