//
// RMA.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RMA: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case requested = "requested"
        case approved = "approved"
        case refunded = "refunded"
        case rejected = "rejected"
    }
    public var id: UUID
    public var orderId: UUID
    public var customerId: UUID
    public var status: Status? = .requested
    public var reason: String
    public var refundAmount: Int?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, orderId: UUID, customerId: UUID, status: Status? = .requested, reason: String, refundAmount: Int? = nil, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.orderId = orderId
        self.customerId = customerId
        self.status = status
        self.reason = reason
        self.refundAmount = refundAmount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case orderId = "order_id"
        case customerId = "customer_id"
        case status
        case reason
        case refundAmount = "refund_amount"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(orderId, forKey: .orderId)
        try container.encode(customerId, forKey: .customerId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(reason, forKey: .reason)
        try container.encodeIfPresent(refundAmount, forKey: .refundAmount)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RMA: Identifiable {}
