//
// Wishlist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Wishlist: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var customerId: UUID
    public var productId: UUID
    public var createdAt: Date

    public init(id: UUID, customerId: UUID, productId: UUID, createdAt: Date) {
        self.id = id
        self.customerId = customerId
        self.productId = productId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case customerId = "customer_id"
        case productId = "product_id"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(productId, forKey: .productId)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Wishlist: Identifiable {}
