//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DefaultAPI {

    /**
     Submit a guest order
     
     - parameter guestCheckout: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiCheckoutGuestPost(guestCheckout: GuestCheckout? = nil, apiResponseQueue: DispatchQueue = AuraApiSDKAPI.apiResponseQueue, completion: @escaping ((_ data: ApiCheckoutGuestPost200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return apiCheckoutGuestPostWithRequestBuilder(guestCheckout: guestCheckout).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submit a guest order
     - POST /api/checkout/guest
     - Guest checkout
     - parameter guestCheckout: (body)  (optional)
     - returns: RequestBuilder<ApiCheckoutGuestPost200Response> 
     */
    open class func apiCheckoutGuestPostWithRequestBuilder(guestCheckout: GuestCheckout? = nil) -> RequestBuilder<ApiCheckoutGuestPost200Response> {
        let localVariablePath = "/api/checkout/guest"
        let localVariableURLString = AuraApiSDKAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: guestCheckout)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiCheckoutGuestPost200Response>.Type = AuraApiSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     List products
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func apiProductsGet(apiResponseQueue: DispatchQueue = AuraApiSDKAPI.apiResponseQueue, completion: @escaping ((_ data: [Product]?, _ error: Error?) -> Void)) -> RequestTask {
        return apiProductsGetWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     List products
     - GET /api/products
     - Get all products
     - returns: RequestBuilder<[Product]> 
     */
    open class func apiProductsGetWithRequestBuilder() -> RequestBuilder<[Product]> {
        let localVariablePath = "/api/products"
        let localVariableURLString = AuraApiSDKAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Product]>.Type = AuraApiSDKAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
